name: rithu
on:
  workflow_dispatch:
jobs:
  today:
    runs-on: ubuntu-latest
    steps:
      - name: complete task
        run: echo "do ur assignment"
      - name: checkout code
        uses: actions/checkout@v3
      - name: show date
        run: date
      - name: list files
        run: ls -a 
      - name: list detailed files
        run: ls -la  
      - name: show directory
        run: uname -a 