name: rithu
on:
  workflow_dispatch:
jobs:
  today:
    runs-on: ubuntu-latest
    steps:
      - name: complete task
        run: echo "do ur assignment"
      - name: show date
        run: date
      - name: list files
        run: ls 
      - name: show directory
        run: uname -a 